name: Catch up with Hugo
on:
  workflow_dispatch:
    schedule:
      # Runs at 18:50 JST every day
      - cron: "50 9 * * *"
jobs:
  main:
    name: Run the update script
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Run update script
      run: ./script/update.sh
