name: Test
on:
  pull_request:
jobs:
  main:
    name: Run a test build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Run test
      run: ./script/test.sh
