name: Test build
on:
  push:
    branches:
      - 'update/**'
jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: ./script/test.sh
